// Default Jobs (Demo-Daten)
(function () {
  const JM = window.JM;

  JM.DEFAULT_JOBS = [
    {
      id: "job-1",
      company: "RemoteSupport24",
      title: "Kundenservice Chat (Remote)",
      description: "Du beantwortest Kundenfragen per Chat. Einfache Prozesse, klare Textbausteine, Einarbeitung inklusive.",
      pay: 15.0,
      hoursPerWeek: 8,
      category: "Support",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Stabile Internetverbindung", "Deutsch C1", "Zuverlässigkeit"],
      link: "#",
      createdAt: "2025-12-01T10:00:00.000Z",
      featured: true
    },
    {
      id: "job-2",
      company: "CreatorBoost",
      title: "TikTok / Reels Content Assistant",
      description: "Unterstütze beim Schneiden, Captioning und Planen von Kurzvideos. Remote, kreative Aufgaben, klare Briefings.",
      pay: 20.0,
      hoursPerWeek: 6,
      category: "Social Media",
      language: "DE",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Basis-Video-Editing", "Pünktlichkeit", "Kommunikation"],
      link: "#",
      createdAt: "2025-11-20T09:00:00.000Z",
      featured: false
    },
    {
      id: "job-3",
      company: "DataClean GmbH",
      title: "Datenpflege / Excel (Remote)",
      description: "Daten aus PDFs/Listen in Tabellen übertragen, Dubletten prüfen, einfache Qualitätssicherung.",
      pay: 12.0,
      hoursPerWeek: 10,
      category: "Datenpflege",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Excel-Grundkenntnisse", "Sorgfalt", "PC/Laptop"],
      link: "#",
      createdAt: "2025-10-12T12:00:00.000Z",
      featured: false
    },
    {
      id: "job-4",
      company: "Labelify AI",
      title: "AI-Tasks: Text Labeling (Remote)",
      description: "Du klassifizierst kurze Textausschnitte nach klaren Regeln. Perfekt als Nebenjob, flexibel planbar.",
      pay: 17.5,
      hoursPerWeek: 4,
      category: "AI-Tasks",
      language: "EN",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Englisch B2", "Genauigkeit", "Zuverlässigkeit"],
      link: "#",
      createdAt: "2025-12-10T07:00:00.000Z",
      featured: true
    },
    {
      id: "job-5",
      company: "SalesSprint",
      title: "Outbound Lead Research (Remote)",
      description: "Du recherchierst passende Leads und pflegst Kontaktlisten. Kein Cold Calling – nur Recherche & Struktur.",
      pay: 14.0,
      hoursPerWeek: 7,
      category: "Vertrieb",
      language: "EN",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Google/LinkedIn Recherche", "Saubere Dokumentation", "Englisch B1+"],
      link: "#",
      createdAt: "2025-09-05T15:00:00.000Z",
      featured: false
    },
    {
      id: "job-6",
      company: "RemoteSupport24",
      title: "Kundenservice Chat (Remote)",
      description: "Du beantwortest Kundenfragen per Chat. Einfache Prozesse, klare Textbausteine, Einarbeitung inklusive.",
      pay: 15.0,
      hoursPerWeek: 8,
      category: "Support",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Stabile Internetverbindung", "Deutsch C1", "Zuverlässigkeit"],
      link: "#",
      createdAt: "2025-12-02T10:00:00.000Z",
      featured: false
    },
    {
      id: "job-7",
      company: "ContentFlow",
      title: "Instagram Post Scheduler",
      description: "Plane und veröffentliche Instagram-Posts nach klaren Vorgaben. Kein Community-Management.",
      pay: 16.0,
      hoursPerWeek: 5,
      category: "Social Media",
      language: "DE",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Meta Business Suite", "Strukturierte Arbeitsweise"],
      link: "#",
      createdAt: "2025-12-03T09:00:00.000Z",
      featured: false
    },
    {
      id: "job-8",
      company: "SheetPro",
      title: "Excel Datenübertragung",
      description: "Übertrage strukturierte Daten aus PDFs in Excel-Tabellen. Klare Vorgaben.",
      pay: 13.0,
      hoursPerWeek: 8,
      category: "Datenpflege",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Excel Basics", "Sorgfältiges Arbeiten"],
      link: "#",
      createdAt: "2025-12-04T11:00:00.000Z",
      featured: false
    },
    {
      id: "job-9",
      company: "AnnotateAI",
      title: "AI Text Annotation",
      description: "Markiere Texte nach vorgegebenen Regeln für KI-Trainingsdaten.",
      pay: 18.0,
      hoursPerWeek: 4,
      category: "AI-Tasks",
      language: "EN",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Englisch B2", "Genauigkeit"],
      link: "#",
      createdAt: "2025-12-05T07:30:00.000Z",
      featured: true
    },
    {
      id: "job-10",
      company: "LeadStack",
      title: "LinkedIn Lead Recherche",
      description: "Recherche von Unternehmen und Ansprechpartnern auf LinkedIn. Kein Kontakt mit Leads.",
      pay: 14.5,
      hoursPerWeek: 7,
      category: "Vertrieb",
      language: "EN",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["LinkedIn Erfahrung", "Saubere Dokumentation"],
      link: "#",
      createdAt: "2025-12-06T14:00:00.000Z",
      featured: false
    },
    {
      id: "job-11",
      company: "HelpDeskNow",
      title: "E-Mail Kundenservice",
      description: "Bearbeitung von Kundenanfragen per E-Mail anhand von Vorlagen.",
      pay: 15.5,
      hoursPerWeek: 9,
      category: "Support",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Deutsch C1", "Strukturierte Kommunikation"],
      link: "#",
      createdAt: "2025-12-07T10:00:00.000Z",
      featured: false
    },
    {
      id: "job-12",
      company: "VideoBoost",
      title: "YouTube Thumbnail Assistant",
      description: "Erstellung einfacher Thumbnails nach festen Layouts. Keine Designkenntnisse nötig.",
      pay: 17.0,
      hoursPerWeek: 5,
      category: "Social Media",
      language: "EN",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Canva Basics", "Kreativität"],
      link: "#",
      createdAt: "2025-12-08T16:00:00.000Z",
      featured: false
    },
    {
      id: "job-13",
      company: "CleanDataOps",
      title: "Datenvalidierung (Remote)",
      description: "Überprüfung bestehender Datensätze auf Vollständigkeit und Korrektheit.",
      pay: 13.5,
      hoursPerWeek: 10,
      category: "Datenpflege",
      language: "DE",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Detailgenauigkeit", "Excel-Grundkenntnisse"],
      link: "#",
      createdAt: "2025-12-09T08:00:00.000Z",
      featured: false
    },
    {
      id: "job-14",
      company: "SmartLabel",
      title: "AI Image Tagging",
      description: "Vergabe von Tags für Bilder nach klar definierten Kriterien.",
      pay: 19.0,
      hoursPerWeek: 3,
      category: "AI-Tasks",
      language: "EN",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Englisch B2", "Genauigkeit"],
      link: "#",
      createdAt: "2025-12-10T09:30:00.000Z",
      featured: true
    },
    {
      id: "job-15",
      company: "SalesAssist",
      title: "CRM Datenpflege",
      description: "Pflege und Aktualisierung von CRM-Datensätzen nach festen Regeln.",
      pay: 14.0,
      hoursPerWeek: 8,
      category: "Vertrieb",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["CRM-Grundverständnis", "Sorgfalt"],
      link: "#",
      createdAt: "2025-12-11T13:00:00.000Z",
      featured: false
    },
    {
      id: "job-16",
      company: "SupportFlow",
      title: "Live-Chat Support (Wochenende)",
      description: "Betreuung von Kundenanfragen per Live-Chat am Wochenende. Klare Prozesse, kein Telefon.",
      pay: 16.0,
      hoursPerWeek: 5,
      category: "Support",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Deutsch C1", "Wochenend-Verfügbarkeit"],
      link: "#",
      createdAt: "2025-12-12T09:00:00.000Z",
      featured: false
    },
    {
      id: "job-17",
      company: "SocialPilot",
      title: "Facebook Post Assistant",
      description: "Vorbereitung und Planung von Facebook-Posts nach festen Redaktionsplänen.",
      pay: 15.0,
      hoursPerWeek: 6,
      category: "Social Media",
      language: "DE",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Facebook Basics", "Zuverlässigkeit"],
      link: "#",
      createdAt: "2025-12-13T11:00:00.000Z",
      featured: false
    },
    {
      id: "job-18",
      company: "TableFix",
      title: "Excel Qualitätsprüfung",
      description: "Prüfung bestehender Excel-Tabellen auf Fehler und Inkonsistenzen.",
      pay: 13.5,
      hoursPerWeek: 9,
      category: "Datenpflege",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Excel-Grundkenntnisse", "Genauigkeit"],
      link: "#",
      createdAt: "2025-12-14T10:30:00.000Z",
      featured: false
    },
    {
      id: "job-19",
      company: "TextMind AI",
      title: "AI Text Klassifizierung",
      description: "Einordnung kurzer Texte für KI-Modelle anhand klarer Vorgaben.",
      pay: 18.5,
      hoursPerWeek: 4,
      category: "AI-Tasks",
      language: "EN",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Englisch B2+", "Aufmerksamkeit"],
      link: "#",
      createdAt: "2025-12-15T08:00:00.000Z",
      featured: true
    },
    {
      id: "job-20",
      company: "PipelineSales",
      title: "B2B Lead Liste erstellen",
      description: "Recherche von B2B-Unternehmen und Pflege strukturierter Lead-Listen.",
      pay: 14.0,
      hoursPerWeek: 8,
      category: "Vertrieb",
      language: "EN",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Recherche-Skills", "Saubere Dokumentation"],
      link: "#",
      createdAt: "2025-12-16T14:00:00.000Z",
      featured: false
    },
    {
      id: "job-21",
      company: "MailCare",
      title: "E-Mail Support Agent",
      description: "Bearbeitung von Support-Anfragen per E-Mail anhand von Vorlagen.",
      pay: 15.5,
      hoursPerWeek: 7,
      category: "Support",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Gute Ausdrucksweise", "Zuverlässigkeit"],
      link: "#",
      createdAt: "2025-12-17T09:30:00.000Z",
      featured: false
    },
    {
      id: "job-22",
      company: "ClipFactory",
      title: "Short-Video Beschreibung schreiben",
      description: "Erstellung kurzer Beschreibungen und Hashtags für Reels & Shorts.",
      pay: 16.5,
      hoursPerWeek: 5,
      category: "Social Media",
      language: "DE",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Kreatives Schreiben", "Social-Media-Affinität"],
      link: "#",
      createdAt: "2025-12-18T16:00:00.000Z",
      featured: false
    },
    {
      id: "job-23",
      company: "DataReview",
      title: "Datensatz-Review",
      description: "Überprüfung großer Datensätze auf Vollständigkeit und Plausibilität.",
      pay: 13.0,
      hoursPerWeek: 10,
      category: "Datenpflege",
      language: "DE",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Sorgfalt", "Strukturierte Arbeitsweise"],
      link: "#",
      createdAt: "2025-12-19T08:00:00.000Z",
      featured: false
    },
    {
      id: "job-24",
      company: "VisionTag",
      title: "AI Bildklassifikation",
      description: "Kategorisierung von Bildern für KI-Trainingszwecke.",
      pay: 19.5,
      hoursPerWeek: 3,
      category: "AI-Tasks",
      language: "EN",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Englisch B2", "Genaues Arbeiten"],
      link: "#",
      createdAt: "2025-12-20T07:45:00.000Z",
      featured: true
    },
    {
      id: "job-25",
      company: "DealFinder",
      title: "Vertriebsdaten Pflege",
      description: "Aktualisierung und Pflege bestehender Vertriebsdatenbanken.",
      pay: 14.5,
      hoursPerWeek: 8,
      category: "Vertrieb",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["CRM-Grundkenntnisse", "Genauigkeit"],
      link: "#",
      createdAt: "2025-12-21T13:00:00.000Z",
      featured: false
    },
    {
      id: "job-26",
      company: "ChatAssist",
      title: "Kundenchat Frühschicht",
      description: "Beantwortung von Kundenanfragen per Chat in den Morgenstunden.",
      pay: 15.0,
      hoursPerWeek: 6,
      category: "Support",
      language: "DE",
      region: "DE",
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Früh verfügbar", "Zuverlässigkeit"],
      link: "#",
      createdAt: "2025-12-22T06:30:00.000Z",
      featured: false
    },
    {
      id: "job-27",
      company: "PostCraft",
      title: "LinkedIn Text Posts schreiben",
      description: "Verfassen kurzer LinkedIn-Beiträge nach Themenvorgaben.",
      pay: 17.0,
      hoursPerWeek: 4,
      category: "Social Media",
      language: "DE",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Gutes Sprachgefühl", "LinkedIn-Erfahrung"],
      link: "#",
      createdAt: "2025-12-23T10:00:00.000Z",
      featured: false
    },
    {
      id: "job-28",
      company: "SheetLogic",
      title: "Google Sheets Datenpflege",
      description: "Pflege und Aktualisierung von Google-Sheets-Dokumenten.",
      pay: 13.5,
      hoursPerWeek: 9,
      category: "Datenpflege",
      language: "DE",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Google Sheets", "Strukturierte Arbeitsweise"],
      link: "#",
      createdAt: "2025-12-24T11:00:00.000Z",
      featured: false
    },
    {
      id: "job-29",
      company: "LabelCore",
      title: "AI Content Review",
      description: "Überprüfung von KI-generierten Inhalten nach Qualitätskriterien.",
      pay: 20.0,
      hoursPerWeek: 3,
      category: "AI-Tasks",
      language: "EN",
      region: "GLOBAL",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Englisch C1", "Analytisches Denken"],
      link: "#",
      createdAt: "2025-12-25T09:00:00.000Z",
      featured: true
    },
    {
      id: "job-30",
      company: "SalesTracker",
      title: "CRM Reporting Assistant",
      description: "Erstellung einfacher Reports aus bestehenden CRM-Daten.",
      pay: 15.0,
      hoursPerWeek: 7,
      category: "Vertrieb",
      language: "DE",
      region: "EU",
      imageUrl: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=200&h=200&q=60",
      requirements: ["Excel oder Sheets", "Grundverständnis CRM"],
      link: "#",
      createdAt: "2025-12-26T14:30:00.000Z",
      featured: false
    }
  ];
})();
